# -*- coding: utf-8 -*-
"""QMB4400-NLTK .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x84k8iYnFWb74HbodyyjOgeyB4kuAuy9

# **Module 06 QMB 4400**

<hr>

### Asignment Module 6:
You recently started working as a data analyst and need to analyze the data using NLTK. You need to analyze the paragraph below and assign a “Minnesota” keyword as a stop words.

**You need to perform following tasks:**
- Tokenized words
- Print the filtered list without “Minnesota” keyword.


**For your submission, include the following:**
- The original script.
- An output screenshot.
"""

# Install NLTK packages
! pip install nltk

# Download NLTK resources
nltk.download('stopwords')

# Assign import variables 
from nltk import word_tokenize
from nltk.corpus import stopwords
import pandas as pd
import numpy as np

# Add Minnesota to stop words list
all_stopwords = stopwords.words('english')
all_stopwords.append('Minnesota')

# verify new stopwords list
print(all_stopwords)

# Add assignment paragraph to a variable 
text = """ This school was founded in 1900 by Peter Mullin as the Mullin Practical School of Business located in Stillwater Minnesota Mullin believed that the need for skilled professionals by the local business community was not being met
The first classes were held in September 1900 With the advent of women's suffrage in 1920 through the passage of the Nineteenth Amendment the school’s female enrollment began to increase
"""

# tokenize data
tko = word_tokenize(text)

# Validate tokinized data
print(tko)

# loop through NLTK and proccess data
stopwords = [x for x in tko if x not in all_stopwords]
# Print filtered list without stop words
print(stopwords)

# Add Final stopwords to a dataframe to validate assignment
df = pd. DataFrame(stopwords)
print(
df.describe() ,
"\n List of tokinized words without Minnesota \n",
df.value_counts())