# -*- coding: utf-8 -*-
"""QMB4400-MOD5_DisplayingDataVisulizations.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zq_7SEbJHDa8sp8odvecFzDDC6ktuVnw

# **Displaying Data Visulizations**

# **Module 05 Assignment - Storing Output**

<hr>

### Assignment Module 5:
You are working as a software developer for the FDA. You need to determine the highest calories in the McDonald's menu. Please use Module_4_Assignment Dataset to complete, which is located on the Course Files page. 

You need to create a script that can perform following tasks.

- Step 1: Read the data from CSV file.
- Step 2: Use matplotlib to generate the chart.
- Step 3: X-axis should be Item and Y axis should be total Calories from Fat.
- Step 4: Draw the line chart using matplotlib.

### **Importing Libaries**
"""

# loading libraries
import sqlite3 as sql
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn
from matplotlib.backends.backend_pdf import PdfPages

"""### **Import Dataset**"""

# Load data to dataframe
df = pd.read_csv('/content/menu.csv', encoding='iso-8859-1')

"""### **Check Data**"""

# Check Data
df.head()

#Double Check DataTypes
df.dtypes

"""### **Clean Data**"""

#counts all null values in data frame (both column and rows)
print('Total NaN Values in Dataframe:' , df.isnull().sum().sum())

"""### **Transform and Proccess Data**"""

# Seperate categorical Varibles
obj_df = df.select_dtypes(include=['object']).copy()
obj_df.head()

#  Convert a column to a category
obj_df["Item"] = obj_df["Item"].astype('category')
obj_df.dtypes

# Encode category colum feature
obj_df["Item_cat"] = obj_df["Item"].cat.codes
obj_df.head()

"""### **Visulize Data**"""

# Use encoded column vector and orginal feeature Calories as X & Y varibles
x = obj_df['Item_cat']
y = df['Calories']



# Setup PDF output file for chart
with PdfPages(r'/content/Mod5Chartpdf') as export_pdf:
  # Plot line graph with trend line for better visulization
  plot = df.plot.line(x='Item', y='Calories',  figsize=[18,8], colormap='spring', title="Highest calories in the McDonald's menu")
  #Plot Trend Line
  z = np.polyfit(x, y, 1)
  p = np.poly1d(z)
  plt.plot(x,p(x),"r--")
  #Plot X & Y Axis labels
  plt.xlabel('Items', fontsize=14)
  plt.ylabel('Total Calories', fontsize=14)
  # Plot grid
  plt.grid(True)
  # Send plot to PDF with data output:
  export_pdf.savefig()